import type { ReactNode } from "react";
import { useEffect } from "react";
import { BadgeCheck, Scale } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const Section = ({ title, children }: { title: string; children: ReactNode }) => (
  <section className="mb-10">
    <h2 className="text-xl font-semibold text-[#0F172A] mb-3">{title}</h2>
    <div className="text-[#64748B] leading-relaxed space-y-3">{children}</div>
  </section>
);

const TermsOfUsePage = () => {
  useEffect(() => {
    window.scrollTo({ top: 0, left: 0, behavior: "smooth" });
  }, []);

  return (
    <div className="min-h-screen bg-[linear-gradient(180deg,_#f8fafc_0%,_#fff7ed_45%,_#ffffff_100%)]">
      <Navbar />
      <div className="relative overflow-hidden">
        <div className="absolute inset-x-0 top-0 h-72 bg-[radial-gradient(circle_at_top,_rgba(217,119,6,0.14),_transparent_65%)] pointer-events-none" />
        <div className="max-w-4xl mx-auto px-6 pt-28 pb-20">
          <div className="rounded-[28px] border border-white/70 bg-white/85 p-8 shadow-[0_24px_80px_rgba(15,23,42,0.08)] backdrop-blur md:p-10">
            <div className="flex flex-col gap-8 border-b border-[#E2E8F0] pb-10 md:flex-row md:items-end md:justify-between">
              <div className="max-w-2xl">
                <span className="inline-flex items-center gap-2 rounded-full border border-[#FED7AA] bg-[#FFF7ED] px-4 py-1.5 text-xs font-semibold uppercase tracking-[0.2em] text-[#C2410C]">
                  <Scale size={14} />
                  Terms of Use
                </span>
                <h1 className="mt-5 text-4xl font-semibold tracking-tight text-[#0F172A] md:text-5xl">
                  Clear terms for using Asset72
                </h1>
                <p className="mt-5 text-lg leading-8 text-[#64748B]">
                  These Terms of Use govern access to and use of Asset72, a platform developed by
                  Golden Hills. By accessing or using the platform, you agree to these terms.
                </p>
              </div>
              <div className="rounded-2xl border border-[#FED7AA] bg-[linear-gradient(135deg,_#FFF7ED,_#FFFBEB)] p-6 md:max-w-xs">
                <p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#C2410C]">
                  Summary
                </p>
                <p className="mt-3 text-base leading-7 text-[#334155]">
                  The platform supports analysis and decision-making, but final business and
                  investment decisions remain with the user.
                </p>
              </div>
            </div>

            <div className="mt-8 grid gap-4 md:grid-cols-2">
              {[
                "Use the platform lawfully and responsibly",
                "Upload only materials you are authorized to share",
                "Treat AI output as analytical support, not legal or financial advice",
                "Respect Golden Hills intellectual property and platform rights",
              ].map((item) => (
                <div
                  key={item}
                  className="flex items-start gap-3 rounded-2xl border border-[#E2E8F0] bg-[#FFFBEB] px-4 py-4"
                >
                  <BadgeCheck className="mt-0.5 text-[#C2410C]" size={18} />
                  <p className="text-sm leading-6 text-[#475569]">{item}</p>
                </div>
              ))}
            </div>

            <div className="mt-10">
              <Section title="Use of the Platform">
                <p>
                  Asset72 provides analytical tools and insights to support real estate investment
                  analysis. The platform is intended for informational and analytical purposes only.
                </p>
                <p>
                  Users agree to use the platform in compliance with applicable laws and not to
                  misuse or attempt to disrupt the service.
                </p>
              </Section>

              <Section title="User Content">
                <p>
                  Users may upload documents such as Offering Memorandums, Rent Rolls, and financial
                  statements for analysis within the platform.
                </p>
                <p>
                  By uploading documents, users confirm they have the right to use and submit such
                  materials. Users remain responsible for the content they upload.
                </p>
              </Section>

              <Section title="AI-Generated Insights">
                <p>
                  Insights generated by the platform are based on data analysis and machine learning
                  models.
                </p>
                <p>
                  These insights are intended to support analysis but do not constitute financial,
                  legal, or investment advice. Users should independently evaluate any investment
                  decisions.
                </p>
              </Section>

              <Section title="Intellectual Property">
                <p>
                  All platform content, software, and technology are the property of Golden Hills
                  and may not be copied, distributed, or reproduced without permission.
                </p>
              </Section>

              <Section title="Limitation of Liability">
                <p>
                  Golden Hills is not responsible for investment decisions made using insights
                  generated by the platform. The platform is provided on an "as-is" basis without
                  guarantees of accuracy or completeness.
                </p>
              </Section>

              <Section title="Changes to Terms">
                <p>
                  Golden Hills may update these Terms of Use from time to time. Continued use of the
                  platform after changes indicates acceptance of the updated terms.
                </p>
              </Section>
            </div>

            <section className="pt-6 border-t border-[#E2E8F0]">
              <h2 className="text-xl font-semibold text-[#0F172A] mb-3">Contact</h2>
              <p className="text-[#64748B] leading-relaxed">
                For questions regarding these terms, please contact:
                <br />
                <span className="text-[#0F172A] font-medium">Golden Hills Capital India Pvt Ltd</span>
                <br />
                <a href="mailto:asset72@ghills.ai" className="text-[#C2410C] hover:underline">
                  asset72@ghills.ai
                </a>
              </p>
            </section>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default TermsOfUsePage;
