/** @type {import('tailwindcss').Config} */
const cssColor = (variable) => `rgb(var(${variable}) / <alpha-value>)`;

const sharedColors = {
  background: cssColor('--background'),
  foreground: cssColor('--foreground'),
  card: cssColor('--card'),
  'card-foreground': cssColor('--card-foreground'),
  popover: cssColor('--popover'),
  'popover-foreground': cssColor('--popover-foreground'),
  primary: cssColor('--primary'),
  'primary-foreground': cssColor('--primary-foreground'),
  secondary: cssColor('--secondary'),
  'secondary-foreground': cssColor('--secondary-foreground'),
  muted: cssColor('--muted'),
  'muted-foreground': cssColor('--muted-foreground'),
  accent: cssColor('--accent'),
  'accent-foreground': cssColor('--accent-foreground'),
  destructive: cssColor('--destructive'),
  'destructive-foreground': cssColor('--destructive-foreground'),
  border: cssColor('--border'),
  input: cssColor('--input'),
  ring: cssColor('--ring'),
};

const sidebarColors = {
  'sidebar-background': cssColor('--sidebar-background'),
  'sidebar-foreground': cssColor('--sidebar-foreground'),
  'sidebar-primary': cssColor('--sidebar-primary'),
  'sidebar-primary-foreground': cssColor('--sidebar-primary-foreground'),
  'sidebar-accent': cssColor('--sidebar-accent'),
  'sidebar-accent-foreground': cssColor('--sidebar-accent-foreground'),
  'sidebar-border': cssColor('--sidebar-border'),
  'sidebar-ring': cssColor('--sidebar-ring'),
};

const vertexColors = {
  'vertex-navy': cssColor('--vertex-navy'),
  'vertex-navy-light': cssColor('--vertex-navy-light'),
  'vertex-emerald': cssColor('--vertex-emerald'),
  'vertex-emerald-light': cssColor('--vertex-emerald-light'),
  'vertex-emerald-glow': cssColor('--vertex-emerald-glow'),
  'vertex-soft-bg': cssColor('--vertex-soft-bg'),
  'vertex-soft-bg-alt': cssColor('--vertex-soft-bg-alt'),
  'vertex-glass': cssColor('--vertex-glass'),
};

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f6f8ff',
        foreground: '#0c1a3b',
        card: '#ffffff',
        'card-foreground': '#0c1a3b',
        popover: '#ffffff',
        'popover-foreground': '#0c1a3b',
        primary: '#0a1b54',
        'primary-foreground': '#ffffff',
        secondary: '#1ebc9a',
        'secondary-foreground': '#0c1a3b',
        muted: '#edf0fb',
        'muted-foreground': '#5b647f',
        accent: '#86e0cf',
        'accent-foreground': '#0c1a3b',
        destructive: '#ff5a5f',
        'destructive-foreground': '#ffffff',
        border: '#d7e2fb',
        input: '#d7e2fb',
        ring: '#1ebc9a',
        'sidebar-background': '#f8f9ff',
        'sidebar-foreground': '#0c1a3b',
        'sidebar-primary': '#0b1b54',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#1ebc9a',
        'sidebar-accent-foreground': '#ffffff',
        'sidebar-border': '#d7e2fb',
        'sidebar-ring': '#1ebc9a',
        'vertex-navy': '#0a1b54',
        'vertex-navy-light': '#1b2d70',
        'vertex-emerald': '#1ebc9a',
        'vertex-emerald-light': '#5de0c4',
        'vertex-emerald-glow': '#ccf7ef',
        'vertex-soft-bg': '#f8fafe',
        'vertex-soft-bg-alt': '#f3f6ff',
        'vertex-glass': '#ffffff',
      },
    },
  },
  plugins: [],
};
